#!/bin/env bash



# I NEED A SET_PATH_FOR_BIN FUNCTION







function list_modules () {
# Get different modules of the desktop environment
while read -r line; do
  if [[ "${line::1}" == _ ]]; then :
  else
  echo "$line"
  fi
done <<< "$(ls -d -- */ | sed 's/\///')
"
}
