anchor_to_edges = true
# icon_theme = "Paper"
position = "top"
height = 30

ironvar_defaults = {  vol = "..." }

[[start]]
type = "clock"


[[center]]
all_monitors = true
favorites = ["1","2","3","4","5","6","7","8","9","10"]
type = "workspaces"

[[end]]
name = "volume"
type = "label"
label = "vol: #vol {{ironbar set vol $(~/.dotfiles/ironbar/volume/get >&2)}}"
on_scroll_up = "~/.dotfiles/ironbar/volume/set --up >&2 && ironbar set vol $( ~/.dotfiles/ironbar/volume/get )"
on_scroll_down = "~/.dotfiles/ironbar/volume/set --down >&2 && ironbar set vol $( ~/.dotfiles/ironbar/volume/get )"

[[end]]
music_dir = "/home/jake/Music"
player_type = "mpd"
type = "music"

[end.truncate]
max_length = 100
mode = "end"

[[end]]
cmd = "/home/jake/bin/phone-battery"
type = "script"

[end.show_if]
cmd = "/home/jake/bin/phone-connected"
interval = 500

# [[end]]
# format = [
#     " {cpu_percent}% | {temp_c:k10temp_Tccd1}°C",
#     " {memory_used} / {memory_total} GB ({memory_percent}%)",
#     "| {swap_used} / {swap_total} GB ({swap_percent}%)",
#     "󰋊 {disk_used:/} / {disk_total:/} GB ({disk_percent:/}%)",
#     "󰓢 {net_down:enp39s0} / {net_up:enp39s0} Mbps",
#     "󰖡 {load_average:1} | {load_average:5} | {load_average:15}",
#     "󰥔 {uptime}",
# ]
# type = "sys_info"
#
# [end.interval]
# cpu = 1
# disks = 300
# memory = 30
# networks = 3
# temps = 5

[[end]]
max_items = 3
type = "clipboard"

[end.truncate]
length = 50
mode = "end"

[[end]]
class = "power-menu"
tooltip = "Up: {{30000:uptime -p | cut -d ' ' -f2-}}"
type = "custom"

[[end.bar]]
label = ""
name = "power-btn"
on_click = "popup:toggle"
type = "button"

[[end.popup]]
orientation = "vertical"
type = "box"

[[end.popup.widgets]]
label = "Power menu"
name = "header"
type = "label"

[[end.popup.widgets]]
type = "box"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='40pt'></span>"
on_click = "!shutdown now"
type = "button"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='40pt'></span>"
on_click = "!reboot"
type = "button"

[[end.popup.widgets]]
label = "Uptime: {{30000:uptime -p | cut -d ' ' -f2-}}"
name = "uptime"
type = "label"

[[end]]
type = "tray"
